name: Repo Audit Action
description: Audit your organization's repositories using Reposaur.

branding:
  icon: shield
  color: purple

inputs:
  policy:
    description: Paths to policies or directory of policies (one path per line)
    required: false
  
  output:
    description: Directory to output reports
    required: false

  max-errors:
    description: Maximum number of errors to ignore before aborting (0 == infinite)
    required: false
    default: '0'

runs:
  using: composite
  steps:
    - id: action
      run: go run main.go -inputs '${{ toJSON(inputs) }}'
      working-directory: ${{ github.action_path }}
      shell: bash