name: Repo Audit Action
description: Audit your organization's repositories using Reposaur.

inputs:
  policy-paths:
    description: Policy Paths
    required: false
    default: '.'

outputs:
  reports:
    description: Generated SARIF reports (JSON array)
    value: ${{ steps.action.outputs.reports }}
  
  repos:
    description: Array of repositories audited
    value: ${{ steps.action.outputs.repos }}

runs:
  using: composite
  steps:
    - id: action
      run: go run main.go -inputs '${{ toJSON(inputs) }}'
      working-directory: ${{ github.action_path }}
      shell: bash